language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
  - xbuild Tdd-Toolkit.xbuild
  - nunit-console ./TddToolkitSpecification/bin/Release/TddToolkitSpecification -exclude Integration,NotWorkingOnMono
